"""
Django settings for meiduo_shop project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-vqkjqctwuza2kgjbn18r68g+*6u4!pz=@b5zci%zu%5!$st346"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['www.meiduo.site','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.users",
    'corsheaders',
    "apps.oauth",
    "apps.areas",
    "apps.goods",
    "apps.contents",
    "django_crontab",
    "apps.carts",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',#允许跨域访问
    'django.middleware.common.CommonMiddleware',
    "django.middleware.security.SecurityMiddleware",
    #用户请求过来后从数据库redis解析sessionid，获取对应的session数据添加到request中
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    #django默认开启了crsf防护,下面我把它注释了
    # "django.middleware.csrf.CsrfViewMiddleware",
    #下面的中间件可以获取request.user
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "meiduo_shop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR,'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "meiduo_shop.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "HOST":  "127.0.0.1",
        "PORT": "3306",
        "NAME": "meiduo_mall",
        "USER": "itcast",
        "PASSWORD": "123456",
    },
    "slave": {
        "ENGINE": "django.db.backends.mysql",
        "HOST":  "127.0.0.1",
        "PORT": "8306",
        "NAME": "meiduo_mall",
        "USER": "root",
        "PASSWORD": "123456",
    }
}
DATABASE_ROUTERS = ["utils.db_router.Router"]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
######redis缓存###########
CACHES = {
    "default": {#预留数据库
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "session": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "code": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "history": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/3",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "carts": {
        #保存购物车数据
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/4",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "goods_count": {
        #保存商品每日访问量
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/5",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
LOGGING = {
   'version': 1,
   'disable_existing_loggers': False,
   'formatters': {
       'verbose': {
           'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
           'style': '{',
       },
       'simple': {
           'format': '{levelname} {message}',
           'style': '{',
       },
   },
   'handlers': {
       'file': {
           'level': 'INFO',
           'class': 'logging.FileHandler',
           'filename': os.path.join(BASE_DIR, 'logs', 'meiduo_shop.log'),  # 修改这里
       },
   },
   'loggers': {
       'django': {
           'handlers': ['file'],
           'level': 'INFO',
           'propagate': True,
       },
   },
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "session"
# 自定义用户类覆盖系统给出的用户类
AUTH_USER_MODEL = 'users.User'
#配置CORS白名单
CORS_ALLOWED_ORIGINS = [
   "http://localhost:8080",
   "http://127.0.0.1:8080",
    "http://www.meiduo.site:8080",
"http://127.0.0.1:8001",
]
#允许跨域访问携带cookie
CORS_ALLOW_CREDENTIALS = True
#QQ第三方登录参数
#我们申请的网站QQ客户端id
QQ_CLIENT_ID='101474184'
#我们申请的网站QQ客户端私钥
QQ_CLIENT_SECRET='c6ce949e04e12ecc909ae6a8b09b637c'
#我们申请时添加的成功后回调的地址
QQ_REDIRECT_URI='http://www.meiduo.site:8080/oauth_callback.html'
##############邮件发送相关#############
#EMAIL_BACKEND让django哪个类来发送邮件
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'
EMAIL_PORT = 465  # 或 587
EMAIL_USE_SSL = True  # 使用SSL加密
EMAIL_USE_TLS = False  # 如果使用SSL就不要用TLS
EMAIL_HOST_USER = '15612383794@163.com'  # 只保留邮箱地址
EMAIL_HOST_PASSWORD = 'PLsVdNecDeRmXhz8'  # 授权码
DEFAULT_FROM_EMAIL = '每多商城<15612383794@163.com>'  # 发件人显示名称

#fastdfs 的IP地址
MEDIA_URL='http://127.0.0.1:8888/'
###########加载自定义文件存储类###########
#指定自定义的Django文件存储类
DEFAULT_FILE_STORAGE = 'utils.fastdfs.storage.MyStorage'
################es######
HAYSTACK_CONNECTIONS = {
    'default': {
    'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
    'URL': 'http://192.168.220.129:9200/',
    'INDEX_NAME': 'meiduo_haystack',
},
}
#搜索结果数据分页大小
HAYSTACK_SEARCH_RESULTS_PER_PAGE=5
########定时任务##########
"""第一个参数是频次 第二个是定时任务的函数 第三个是日志路径
每次添加新的定时任务，运行python manage.py crontab add  添加
python manage.py crontab show 显示定时任务
python manage.py crontab remove 删除定时任务
"""
CRONJOBS = [
    #分 时 日 月 周
   ('*/1 * * * *','apps.contents.crons.generic_get_index','>>'+os.path.join(BASE_DIR,'logs/cronjobs.log')),
('0 0 * * *','apps.goods.crons.merge_redis_goods_count','>>'+os.path.join(BASE_DIR,'logs/cronjobs.log')),
]