# Generated by Django 4.2.16 on 2026-02-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_goodsvisitcount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsvisitcount",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="统计日期"),
        ),
        migrations.AlterUniqueTogether(
            name="goodsvisitcount",
            unique_together={("category", "date")},
        ),
    ]
